name: Jeroen Janssens
markdown: redcarpet
highlighter: pygments
url: http://www.jeroenjanssens.com
description: Dutch Data Scientist, Toolmaker, Unix Philosopher
description: Independent Data Science Consultant and Trainer
